import type {
  User,
  Instructor,
  Subscription,
  LessonReservation,
  Notification,
  BoardPost,
} from "./types"

export const mockMembers: User[] = [
  {
    id: "m1",
    name: "김민지",
    phone: "010-1234-5678",
    role: "member",
    gender: "female",
    registeredAt: "2025-09-15",
    subscriptionId: "s1",
  },
  {
    id: "m2",
    name: "이준호",
    phone: "010-2345-6789",
    role: "member",
    gender: "male",
    registeredAt: "2025-10-01",
    subscriptionId: "s2",
  },
  {
    id: "m3",
    name: "박서연",
    phone: "010-3456-7890",
    role: "member",
    gender: "female",
    registeredAt: "2025-11-20",
    subscriptionId: "s1",
  },
  {
    id: "m4",
    name: "최현우",
    phone: "010-4567-8901",
    role: "member",
    gender: "male",
    registeredAt: "2026-01-05",
    subscriptionId: "s3",
  },
  {
    id: "m5",
    name: "정수아",
    phone: "010-5678-9012",
    role: "member",
    gender: "female",
    registeredAt: "2026-01-18",
    subscriptionId: "s2",
  },
  {
    id: "m6",
    name: "한지우",
    phone: "010-6789-0123",
    role: "member",
    gender: "female",
    registeredAt: "2026-02-01",
    subscriptionId: "s1",
  },
]

export const mockInstructors: Instructor[] = [
  {
    id: "i1",
    name: "윤선생",
    phone: "010-9876-5432",
    specialty: "클래식",
    registeredAt: "2024-03-01",
    color: "#3a6b52",
  },
  {
    id: "i2",
    name: "장선생",
    phone: "010-8765-4321",
    specialty: "재즈 / 팝",
    registeredAt: "2024-06-15",
    color: "#b87a3d",
  },
  {
    id: "i3",
    name: "이선생",
    phone: "010-7654-3210",
    specialty: "입시 / 클래식",
    registeredAt: "2025-01-10",
    color: "#6b5a3a",
  },
]

export const mockSubscriptions: Subscription[] = [
  {
    id: "s1",
    name: "기본반 (주1회)",
    totalLessons: 4,
    remainingLessons: 4,
    durationMonths: 1,
    price: 200000,
  },
  {
    id: "s2",
    name: "집중반 (주2회)",
    totalLessons: 8,
    remainingLessons: 8,
    durationMonths: 1,
    price: 350000,
  },
  {
    id: "s3",
    name: "마스터반 (주3회)",
    totalLessons: 12,
    remainingLessons: 12,
    durationMonths: 1,
    price: 480000,
  },
]

function getDateStr(dayOffset: number): string {
  const d = new Date()
  d.setDate(d.getDate() + dayOffset)
  return d.toISOString().split("T")[0]
}

export const mockReservations: LessonReservation[] = [
  {
    id: "r1",
    memberId: "m1",
    memberName: "김민지",
    instructorId: "i1",
    instructorName: "윤선생",
    date: getDateStr(0),
    startTime: "14:00",
    endTime: "14:50",
    type: "lesson",
    status: "confirmed",
  },
  {
    id: "r2",
    memberId: "m2",
    memberName: "이준호",
    instructorId: "i2",
    instructorName: "장선생",
    date: getDateStr(0),
    startTime: "16:00",
    endTime: "16:50",
    type: "lesson",
    status: "confirmed",
  },
  {
    id: "r3",
    memberId: "m3",
    memberName: "박서연",
    instructorId: "i1",
    instructorName: "윤선생",
    date: getDateStr(1),
    startTime: "10:00",
    endTime: "10:50",
    type: "lesson",
    status: "confirmed",
  },
  {
    id: "r4",
    memberId: "m4",
    memberName: "최현우",
    instructorId: "i3",
    instructorName: "이선생",
    date: getDateStr(1),
    startTime: "15:00",
    endTime: "15:50",
    type: "lesson",
    status: "pending",
  },
  {
    id: "r5",
    memberId: "m5",
    memberName: "정수아",
    instructorId: "i2",
    instructorName: "장선생",
    date: getDateStr(2),
    startTime: "11:00",
    endTime: "11:50",
    type: "lesson",
    status: "confirmed",
  },
  {
    id: "r6",
    memberId: "m1",
    memberName: "김민지",
    instructorId: "",
    instructorName: "",
    date: getDateStr(3),
    startTime: "14:00",
    endTime: "15:00",
    type: "practice",
    roomNumber: 3,
    status: "confirmed",
  },
  {
    id: "r9",
    memberId: "m2",
    memberName: "이준호",
    instructorId: "",
    instructorName: "",
    date: getDateStr(0),
    startTime: "11:00",
    endTime: "12:00",
    type: "practice",
    roomNumber: 1,
    status: "confirmed",
  },
  {
    id: "r10",
    memberId: "m5",
    memberName: "정수아",
    instructorId: "",
    instructorName: "",
    date: getDateStr(1),
    startTime: "15:00",
    endTime: "16:00",
    type: "practice",
    roomNumber: 5,
    status: "confirmed",
  },
  {
    id: "r11",
    memberId: "m3",
    memberName: "박서연",
    instructorId: "",
    instructorName: "",
    date: getDateStr(0),
    startTime: "18:00",
    endTime: "19:00",
    type: "practice",
    roomNumber: 7,
    status: "confirmed",
  },
  {
    id: "r7",
    memberId: "m6",
    memberName: "한지우",
    instructorId: "i1",
    instructorName: "윤선생",
    date: getDateStr(0),
    startTime: "18:00",
    endTime: "18:50",
    type: "lesson",
    status: "confirmed",
  },
  {
    id: "r8",
    memberId: "m3",
    memberName: "박서연",
    instructorId: "i3",
    instructorName: "이선생",
    date: getDateStr(4),
    startTime: "13:00",
    endTime: "13:50",
    type: "lesson",
    status: "changed",
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    type: "reservation",
    title: "새 레슨 예약",
    message: "김민지 회원이 2/12 14:00 레슨을 예약했습니다.",
    createdAt: getDateStr(0) + "T09:30:00",
    read: false,
  },
  {
    id: "n2",
    type: "change",
    title: "예약 변경 요청",
    message: "박서연 회원이 2/14 레슨 시간 변경을 요청했습니다. (13:00 → 15:00)",
    createdAt: getDateStr(0) + "T08:15:00",
    read: false,
  },
  {
    id: "n3",
    type: "cancel",
    title: "예약 취소",
    message: "최현우 회원이 2/13 15:00 레슨을 취소했습니다.",
    createdAt: getDateStr(-1) + "T17:00:00",
    read: true,
  },
  {
    id: "n4",
    type: "system",
    title: "시스템 알림",
    message: "이준호 회원의 수강권이 3일 후 만료됩니다.",
    createdAt: getDateStr(-1) + "T10:00:00",
    read: true,
  },
]

export const mockPosts: BoardPost[] = [
  {
    id: "p1",
    title: "2월 학원 운영시간 안내",
    content: "2월 한 달간 운영시간이 변경됩니다.\n\n평일: 10:00 ~ 22:00\n주말: 10:00 ~ 18:00\n\n설 연휴 (1/28~1/30)는 휴무입니다.",
    authorName: "관리자",
    createdAt: "2026-02-01",
    pinned: true,
  },
  {
    id: "p2",
    title: "연습실 3번방 피아노 조율 안내",
    content: "연습실 3번방 피아노 조율 작업이 예정되어 있습니다.\n\n일시: 2/15(토) 오전\n해당 시간 3번방 사용이 불가합니다.",
    authorName: "관리자",
    createdAt: "2026-02-08",
    pinned: false,
  },
  {
    id: "p3",
    title: "봄학기 수강 등록 안내",
    content: "3월 봄학기 수강 등록이 시작됩니다.\n\n기존 회원: 2/20부터 등록 가능\n신규 회원: 2/25부터 등록 가능\n\n자세한 내용은 문의 바랍니다.",
    authorName: "관리자",
    createdAt: "2026-02-10",
    pinned: false,
  },
]
